/* <![CDATA[ */window.koko_analytics = {"url":"https:\/\/dvd-flix.com\/wp-admin\/admin-ajax.php?action=koko_analytics_collect","site_url":"https:\/\/dvd-flix.com","post_id":0,"method":"cookie","use_cookie":true};/* ]]> */

/* <![CDATA[ */var dtAjax = {"url":"\/wp-admin\/admin-ajax.php","player_api":"https:\/\/dvd-flix.com\/wp-json\/dooplayer\/v2\/","play_ajaxmd":"1","play_method":"wp_json","googlercptc":null,"classitem":"5","loading":"Loading..","afavorites":"Add to favorites","rfavorites":"Remove of favorites","views":"Views","remove":"Remove","isawit":"I saw it","send":"Data send..","updating":"Updating data..","error":"Error","pending":"Pending review","ltipe":"Download","sending":"Sending data","enabled":"Enable","disabled":"Disable","trash":"Delete","lshared":"Links Shared","ladmin":"Manage pending links","sendingrep":"Please wait, sending data..","ready":"Ready","deletelin":"Do you really want to delete this link?"};/* ]]> */

/* <![CDATA[ */var Datadcacef = ["eyJzcmMiOlsiYUhSMGNITTZMeTl3WVdkbFlXUXlMbWR2YjJkc1pYTjVibVJwWTJGMGFXOXVMbU52YlM5d1lXZGxZV1F2YW5NdllXUnpZbmxuYjI5bmJHVXVhbk09IiwiYUhSMGNITTZMeTl6ZEdGMGFXTXVaRzkxWW14bFkyeHBZMnN1Ym1WMEwybHVjM1J5WldGdEwyRmtYM04wWVhSMWN5NXFjdz09Il0sImJnQ29sb3IiOiJyZ2JhKDI1NSwwLDAsMC43NSkiLCJibHVyIjoib24iLCJidXR0b24iOiJvZmYiLCJidXR0b25TdHlsZSI6IiIsImNhcHRpb24iOiJJIGhhdmUgZGlzYWJsZWQgQWRCbG9ja2VyIiwiY29udGVudCI6IjxwPlBsZWFzZSBkaXNhYmxlIEFkQmxvY2sgdG8gcHJvY2VlZCB0byB0aGUgZGVzdGluYXRpb24gcGFnZS4gXHUwMGEwPFwvcD4iLCJjcm9zcyI6Im9mZiIsImRlYnVnIjoib2ZmIiwiZm9sZGVyIjoiY2ZjY2RmIiwiZ3VpZGUiOiJvZmYiLCJndWlkZVRyYW5zbGF0aW9uIjp7InRyaWdnZXIiOiJIb3cgZG8gSSBkaXNhYmxlIG15IGFkIGJsb2NrZXI\/IiwidHJpZ2dlck9rIjoiT0suIEkgdW5kZXJzdGFuZC4iLCJndWlkZVRpdGxlIjoiVG8gZGlzYWJsZSBhZCBibG9ja2VyIG9uIHRoaXMgc2l0ZToiLCJndWlkZUxpc3QxIjoiUmlnaHQgY2xpY2sgb24gdGhlIGFkIGJsb2NrZXIgZXh0ZW5zaW9uIGljb24gYXQgdGhlIHRvcCByaWdodCBjb3JuZXIgb2YgeW91ciBicm93c2VyIiwiZ3VpZGVMaXN0MiI6IkZyb20gdGhlIG1lbnUgY2hvb3NlIDxiPiZxdW90O0Rpc2FibGUgb24gdGhpcyBzaXRlJnF1b3Q7PFwvYj4gb3IgPGI+JnF1b3Q7UGF1c2Ugb24gdGhpcyBzaXRlJnF1b3Q7IDxcL2I+IiwiZ3VpZGVMaXN0MyI6IlJlZnJlc2ggdGhlIHBhZ2UgaWYgbm90IGF1dG9tYXRpY2FsbHkgcmVmcmVzaGVkIn0sImxvb3AiOiIwIiwibW9kYWxDb2xvciI6InJnYmEoMjU1LDI1NSwyNTUsMSkiLCJvdmVybGF5Ijoib24iLCJvcGVuTGltaXQiOiJvZmYiLCJvcGVuTGltaXRDb3VudCI6NSwicGx1Z2luU3JjIjoiYUhSMGNITTZMeTlrZG1RdFpteHBlQzVqYjIwdmQzQXRZMjl1ZEdWdWRDOXdiSFZuYVc1ekwyUmxZbXh2WTJ0bGNpOD0iLCJwcmVmaXgiOiJkY2FjZWYiLCJyZWRpcmVjdCI6IiIsInJ1bGVzIjpbImVycm9yIiwiYWJvcnQiLCJ0eXBlIiwidXJsIiwiY29udGVudCIsInJlZGlyZWN0IiwiYWRkIl0sInN0eWxlIjoiY29tcGFjdCIsInRleHRDb2xvciI6IiMyMzI4MmQiLCJ0aW1lb3V0IjoiMCIsInRpdGxlIjoiSXQgTG9va3MgTGlrZSBZb3UgSGF2ZSBBZEJsb2NrZXIgRW5hYmxlZCIsInRyYW5zbGF0aW9ucyI6Im9mZiIsImxhbmdKU09OIjoiXCJ7fVwiIiwiYmxhY2tvdXQiOiJmY2ZiZmEiLCJtb2RhbCI6ImFiYmVkZSIsIndyYXBwZXIiOiJhZmZmZGUiLCJmaWx0ZXIiOiJkZmZjZmJmYWFiIn0="];/* ]]> */

window.PerfectyPushOptions = {path: "https://dvd-flix.com/wp-content/plugins/perfecty-push-notifications/public/js",dialogTitle: "Do you want to receive notifications?",dialogSubmit: "Continue",dialogCancel: "Not now",settingsTitle: "Notifications preferences",settingsOptIn: "I want to receive notifications",settingsUpdateError: "Could not change the preference, try again",serverUrl: "https://dvd-flix.com/wp-json/perfecty-push",vapidPublicKey: "BPG-repG4iNJMhDdkHtd9JNkKK6OTyr-MkwFy1rtYOfK347Kv5ZNmiyoZ67C7rFUjs04aDSxO5q006qj012c0d8",token: "36df21b9dd",tokenHeader: "X-WP-Nonce",enabled: true,unregisterConflicts: false,serviceWorkerScope: "/perfecty/push",loggerLevel: "error",loggerVerbose: false,hideBellAfterSubscribe: false,askPermissionsDirectly: true,unregisterConflictsExpression: "(OneSignalSDKWorker|wonderpush-worker-loader|webpushr-sw|subscribers-com\/firebase-messaging-sw|gravitec-net-web-push-notifications|push_notification_sw)",promptIconUrl: "https://dvd-flix.com/wp-content/uploads/2024/07/favicon.gif",visitsToDisplayPrompt: 0}

jQuery(document).ready(function(a){"false"==dtGonza.mobile&&a(window).load(function(){a(".scrolling").mCustomScrollbar({theme:"minimal-dark",scrollInertia:200,scrollButtons:{enable:!0},callbacks:{onTotalScrollOffset:100,alwaysTriggerOffsets:!1}})})});

jQuery(document).ready(function($) {var owl = $("#genre_new-release");owl.owlCarousel({items : 5,autoPlay: 4000,stopOnHover : true,pagination : false,itemsDesktop : [1400,6],itemsDesktopSmall : [1300,5],itemsTablet: [768,4],itemsTabletSmall: false,itemsMobile : [479,3],});$(".next_new-release").click(function(){owl.trigger('owl.prev');})
$(".prev_new-release").click(function(){owl.trigger('owl.next');})
});

jQuery(document).ready(function($) {var owl = $("#genre_new");owl.owlCarousel({items : 5,autoPlay: 4000,stopOnHover : true,pagination : false,itemsDesktop : [1400,6],itemsDesktopSmall : [1300,5],itemsTablet: [768,4],itemsTabletSmall: false,itemsMobile : [479,3],});$(".next_new").click(function(){owl.trigger('owl.prev');})
$(".prev_new").click(function(){owl.trigger('owl.next');})
});

jQuery(document).ready(function($) {var owl = $("#genre_updated");owl.owlCarousel({items : 5,autoPlay: 4000,stopOnHover : true,pagination : false,itemsDesktop : [1400,6],itemsDesktopSmall : [1300,5],itemsTablet: [768,4],itemsTabletSmall: false,itemsMobile : [479,3],});$(".next_updated").click(function(){owl.trigger('owl.prev');})
$(".prev_updated").click(function(){owl.trigger('owl.next');})
});

{"prefetch":[{"source":"document","where":{"and":[{"href_matches":"\/*"},{"not":{"href_matches":["\/wp-*.php","\/wp-admin\/*","\/wp-content\/uploads\/*","\/wp-content\/*","\/wp-content\/plugins\/*","\/wp-content\/themes\/dooplay\/*","\/*\\?(.+)"]}},{"not":{"selector_matches":"a[rel~=\"nofollow\"]"}},{"not":{"selector_matches":".no-prefetch, .no-prefetch a"}}]},"eagerness":"conservative"}]}

jQuery(document).ready(function($) {$("#featured-titles").owlCarousel({ autoPlay:false,items:5,stopOnHover:true,pagination:false,itemsDesktop:[1199,4],itemsDesktopSmall:[980,4],itemsTablet:[768,3],itemsTabletSmall: false,itemsMobile:[479,3] });$(".nextf").click(function(){ $("#featured-titles").trigger("owl.next") });$(".prevf").click(function(){ $("#featured-titles").trigger("owl.prev") });$("#dt-tvshows").owlCarousel({ autoPlay:false,items:5,stopOnHover:true,pagination:false,itemsDesktop:[1199,5],itemsDesktopSmall:[980,5],itemsTablet:[768,4],itemsTabletSmall:false,itemsMobile:[479,3] });$(".next4").click(function(){ $("#dt-tvshows").trigger("owl.next") });$(".prev4").click(function(){ $("#dt-tvshows").trigger("owl.prev") });$("#dt-episodes").owlCarousel({ autoPlay:false,pagination:false,items:3,stopOnHover:true,itemsDesktop:[900,3],itemsDesktopSmall:[750,3],itemsTablet:[500,2],itemsMobile:[320,1] });$(".next").click(function(){ $("#dt-episodes").trigger("owl.next") });$(".prev").click(function(){ $("#dt-episodes").trigger("owl.prev") });$("#dt-seasons").owlCarousel({ autoPlay:false,items:5,stopOnHover:true,pagination:false,itemsDesktop:[1199,5],itemsDesktopSmall:[980,5],itemsTablet:[768,4],itemsTabletSmall:false,itemsMobile:[479,3] });$(".next2").click(function(){ $("#dt-seasons").trigger("owl.next") });$(".prev2").click(function(){ $("#dt-seasons").trigger("owl.prev") });$("#slider-movies").owlCarousel({ autoPlay:false,items:2,stopOnHover:true,pagination:true,itemsDesktop:[1199,2],itemsDesktopSmall:[980,2],itemsTablet:[768,2],itemsTabletSmall:[600,1],itemsMobile:[479,1] });$("#slider-tvshows").owlCarousel({ autoPlay:false,items:2,stopOnHover:true,pagination:true,itemsDesktop:[1199,2],itemsDesktopSmall:[980,2],itemsTablet:[768,2],itemsTabletSmall:[600,1],itemsMobile:[479,1] });$("#slider-movies-tvshows").owlCarousel({ autoPlay:false,items:2,stopOnHover:true,pagination:true,itemsDesktop:[1199,2],itemsDesktopSmall:[980,2],itemsTablet:[768,2],itemsTabletSmall:[600,1],itemsMobile:[479,1] });$(".reset").click(function(event){ if (!confirm( dtGonza.reset_all )) { event.preventDefault() } });$(".addcontent").click(function(event){ if(!confirm(dtGonza.manually_content)){ event.preventDefault() } });});

/* <![CDATA[ */var dtGonza = {"api":"https:\/\/dvd-flix.com\/wp-json\/dooplay\/search\/","glossary":"https:\/\/dvd-flix.com\/wp-json\/dooplay\/glossary\/","nonce":"dc64d9e65d","area":".live-search","button":".search-button","more":"View all results","mobile":"false","reset_all":"Really you want to restart all data?","manually_content":"They sure have added content manually?","loading":"Loading..","loadingplayer":"Loading player..","selectaplayer":"Select a video player","playeradstime":"5","autoplayer":null,"livesearchactive":"1"};/* ]]> */

var uid = '120172';var wid = '659243';var pop_tag = document.createElement('script');pop_tag.src='//cdn.popcash.net/show.js';document.body.appendChild(pop_tag);pop_tag.onerror = function() {pop_tag = document.createElement('script');pop_tag.src='//cdn2.popcash.net/show.js';document.body.appendChild(pop_tag)};